name = "WGPUCore"
uuid = "53d714bf-0d76-4802-84b4-6cb75cca55f5"
authors = ["arhik <arhik23@gmail.com>"]
version = "0.1.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
WGPUNative = "c14bfd16-04f9-4c2f-a915-b355584b5509"

[compat]
CEnum = "^0.5"
Reexport = "^1.2"
WGPUNative = "0.1.3"
julia = "^1.9.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
